/*
 * Copyright 2021 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.kie.kogito;

// L'unité à laquelle appartient cette règle
unit HelloDRLUnit

// Les trucs qu'on utilise
import org.kie.kogito.domain.data_in.Person;
import org.kie.kogito.lib.Log;

// Une règle
rule "Is Adult"
when
    $p: /persons[Age >= isAdultAge];
then
    $p.isAdult = true;
    Log.toConsole("DRL a trouvé un adulte!");
end


// L'unité aura un endpoint "adult" auquel on répondra les personnes
query "adult"
    $p: /persons;
end